### ISSUE TITLE
give hyperlinks better contrast

### ISSUE THREAD

**Issue by yochannah** [intermine/training-portal#4]
right now hyperlinks don't stand out from the text at all, so it can be hard to spot them. Could me (say) make them underlined and a different colour? 

Example - I can only really tell when the link is a link when I hover. 

![image of hyperlink with cursor hovering over it - you can see the link now](https://user-images.githubusercontent.com/9271438/87036527-d6e01200-c1e2-11ea-8f5a-87b2c6790bcd.png)
![image of hyperlink with no hover - it's hard ot tell it's a hyperlink](https://user-images.githubusercontent.com/9271438/87036535-dba4c600-c1e2-11ea-8d43-528cf029c744.png)

**Comment by Persdre** [comment]
yeah, it is a good suggestion!

**Comment by Anisha-28** [comment]
Can i solve this issue for december 2020 @sergiocontrino .. i believe it is already done or not

**Comment by Persdre** [comment]
<img width="313" alt="Screenshot 2020-10-08 at 1 10 20 PM" src="https://user-images.githubusercontent.com/35624031/95417473-b7828d80-0967-11eb-87e4-f9dfcb048357.png">
I already solved this issue :) You can try other improvements! thanks~

**Comment by sergiocontrino** [comment]
oops, we should have closed this one.. i'll do it now.  i'll go through the other issues, @Persdre please let me know if you know of wrongly open ones. thanks!
