### ISSUE TITLE
add intermine logo to header

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/training-portal#7]
it would be nice to have the logo on the green header

**Comment by itolimaesther** [comment]
@sergiocontrino am an outreachy applicant. Can I work on this issue

**Comment by sergiocontrino** [comment]
yes @itolimaesther, thank you!

**Comment by Anisha-28** [comment]
Hi .. can i work on this issue .. @sergiocontrino

**Comment by Anisha-28** [comment]
After making changes and creating a new branch, after the push command it states 
Permission to intermine/training-portal.git denied to Anisha-28.
fatal: unable to access 'https://github.com/intermine/training-portal.git/': The requested URL returned error: 403

**Comment by sergiocontrino** [comment]
hi @Anisha-28 , thank you for looking into this. have you tried doing a pull request (from your fork to this)?

**Comment by Anisha-28** [comment]
![Screen Shot 2020-10-08 at 6 38 42 pm](https://user-images.githubusercontent.com/70424072/95429184-bd8f6300-0995-11eb-92dd-2ee34985ee69.png)


I have added the logo .. but could not do the pull .. @sergiocontrino

**Comment by Anisha-28** [comment]
I have added the logo and created a pull request .. you can have a look if it's fine @sergiocontrino

**Comment by sergiocontrino** [comment]
thank you @Anisha-28, i think the pull request is there, see https://github.com/intermine/training-portal/pulls. thanks!

**Comment by Anisha-28** [comment]
Is there anything else i can do at the moment .. i think there is no more issue for this project @sergiocontrino

**Comment by heralden** [comment]
Fixed with #22
